FROM openjdk:11-jdk

VOLUME /tmp

ARG JAR_FILE=crud-app/target/*.jar
ENV JAVA_OPTS="-Dspring.profiles.active=docker"

COPY ${JAR_FILE} application.jar

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /application.jar"]